# grant all privileges (= use `privileged` SCC) to the CVMFS CSI driver.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cvmfs-csi-privileged-scc
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-csi-privileged-scc
  namespace: {{ .Values.namespace }}
subjects:
# all 3 serviceaccounts used by CVMFS CSI drivers
- kind: ServiceAccount
  name: cvmfs-nodeplugin
  namespace: {{ .Values.namespace }}
- kind: ServiceAccount
  name: cvmfs-attacher
  namespace: {{ .Values.namespace }}
- kind: ServiceAccount
  name: cvmfs-provisioner
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: cvmfs-csi-privileged-scc
  apiGroup: rbac.authorization.k8s.io
